--- #YAML:1.0
name:                Image-Tileset
version:             0.01
abstract:            A tileset loader.
license:             ~
author:              
    - Noah Petherbridge <root@kirsle.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Image::Magick:                 1
    XML::Simple:                   1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
